# Generated by Django 4.0.1 on 2022-01-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='keyword',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
