# Generated by Django 4.0.1 on 2022-01-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0002_candidate_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='repo_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
